name: arXiv daily RSS

on:
  schedule:
    # 11:17 JST = 02:17 UTC
    - cron:  '17 2 * * *'
  workflow_dispatch:
    inputs:
      yymmdd:
        description: '日付 (YYMMDD format, e.g., 250520)'
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v4
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
          
      - name: Install deps
        run: |
          uv sync --no-dev

      - name: Run generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          if [ -n "${{ github.event.inputs.yymmdd }}" ]; then
            uv run src/main.py --yymmdd "${{ github.event.inputs.yymmdd }}"
          else
            uv run src/main.py
          fi

      # 生成ファイルをコミット
      - name: Commit & push RSS
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/index.xml'
          default_author: github_actions
          message: 'chore: update RSS feed'
          push: origin gh-pages --force
